### ISSUE TITLE
Authentication is unnecessarily difficult

### ISSUE THREAD

**Issue by Gerzer** [rcos/rcos_io#29]
Currently, the only way to sign in seems to be to type in your email address, to wait up to 5+ minutes in the worst case (worst  that I’ve experienced so far, that is) to receive an email with a link, and to click on that link. This is highly inefficient, making it unnecessarily difficult to sign in. It’ll be especially problematic when in-person attendance is taken because it will slow down the attendance process, reducing the amount of time that people have to work on their projects. This new RCOS website should at the very least not be a regression from Telescope, which means that it should support authentication with Rensselaer CAS/Shibboleth, Discord, or a password.

**Comment by Apexal** [comment]
Unfortunately, it seems that emails sent to RPI addresses take much longer to arrive than other email providers. Using Gmail, I receive the emails after a few seconds.

A magic link was used as it was quick to implement and worked for all types of users: students, alum, faculty, and external guests.

We can definitely implement more sign-in options, including signing in with Discord/GitHub. Given that the emails take a while to arrive for students, I'll pursue these options. CAS/Shibboleth I'd like to avoid because I don't want the login to depend on an RPI system they can turn off at a whim. It's also a hassle to implement and provides nothing more than the magic link does (email verification). Unless it provides more value than email verification, I think it should be avoided. Let me know if you feel strongly about this though.

**Comment by Apexal** [comment]
Also note that once logged-in, your session remains for a while and you won't have to log in again. The Mentors had to log in again today as I changed the session store from database to a cache so all existing sessions were invalidated.

**Comment by Gerzer** [comment]
> Unfortunately, it seems that emails sent to RPI addresses take much longer to arrive than other email providers. Using Gmail, I receive the emails after a few seconds.
Well, due to #30, the vast majority of users can’t take advantage of that.

> A magic link was used as it was quick to implement and worked for all types of users: students, alum, faculty, and external guests.
>
> We can definitely implement more sign-in options, including signing in with Discord/GitHub. Given that the emails take a while to arrive for students, I'll pursue these options. CAS/Shibboleth I'd like to avoid because I don't want the login to depend on an RPI system they can turn off at a whim. It's also a hassle to implement and provides nothing more than the magic link does (email verification). Unless it provides more value than email verification, I think it should be avoided. Let me know if you feel strongly about this though.
Email verification is a bad solution on its own because it creates significantly more friction, even when emails arrive instantaneously, because you have to context-switch to a different app or website. Discord and GitHub authentication shouldn’t be too difficult to implement since, well, the functionality already exists; it’s just not enabled for initial sign-in. Additionally, adding support for [WebAuthn](https://webauthn.guide/) would be a significant improvement. It dramatically improves security and ease-of-use, especially when there’s an option to disable other forms of authentication (since the overall security is only as good as the weakest link).

**Comment by Apexal** [comment]
Added GitHub and Discord login. WebAuthn would be interesting to pursue, let me know if you're interested in contributing in that area potentially! I haven't worked with it before but am open to checking it out too.
